name: Deploy to IPFS

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Install Dependencies
        run: npm install axios

      - name: Upload to IPFS via Pinata
        run: |
          node <<EOF
          const axios = require('axios');
          const FormData = require('form-data');
          const fs = require('fs');

          const uploadToPinata = async () => {
            const url = `https://api.pinata.cloud/pinning/pinFileToIPFS`;
            const formData = new FormData();
            formData.append('file', fs.createReadStream('./index.html')); // Chemin vers le fichier
            const headers = {
              'Content-Type': `multipart/form-data; boundary=${formData._boundary}`,
              Authorization: `Bearer ${{ secrets.PINATA_API_KEY }}`
            };
            try {
              const response = await axios.post(url, formData, { headers });
              console.log('File successfully uploaded:', response.data);
            } catch (error) {
              console.error('Error uploading file:', error.response?.data || error.message);
            }
          };

          uploadToPinata();
          EOF
